<header>
<link rel="stylesheet" href="public/css/home.css">
</header>

<body id="bg" name="bg">
	<div id="ppDiv" name="ppDiv" style="text-align:center;">
		<button type="button" name="ppIcon" id="ppIcon" onclick="displayPPInfo();"> PP </button>
	</div>
	<div id="infoDiv" name="infoDiv" onclick="infoClicked();" style="text-align:center;">
		<button type="button" name="infoButton" id="infoButton" style="display:none"> Info </button>
	</div>
	<div id="settingsDiv" name="settingsDiv" onclick="settingsClicked();" style="text-align:center;">
		<button type="button" name="settingsButton" id="settingsButton" style="display:none"> Settings </button>
	</div>
</body>

<footer>
	<script src="public/js/home.js"></script>
</footer>
