<header>
<link rel="stylesheet" href="public/css/home.css">
</header>

<body id="bg" name="bg">
	<div id="ppDiv" name="ppDiv" style="text-align:center;">
		<input type="image" src="public/img/main_icon.png" alt="PP" name="ppIcon" id="ppIcon" onclick="displayPPInfo();">
	</div>
	<div id="infoDiv" name="infoDiv" onclick="infoClicked();" style="text-align:center;">
		<input type="image" src="public/img/info_icon.png" name="infoButton" id="infoButton" alt="Info" style="display:none">
	</div>
	<div id="settingsDiv" name="settingsDiv" onclick="settingsClicked();" style="text-align:center;">
		<input type="image" src="public/img/settings_icon.png" name="settingsButton" id="settingsButton" alt="Settings" style="display:none">
	</div>
	<div id="settingsDropDownDiv" name="settingsDropDownDiv" class="styled-select black rounded">
		
		
		<select id="sectionDD" name="sectionDD" style="display:none;">
			<option value="a">Section A</option>
			<option value="b">Section B</option>
			<option value="c">Section C</option>
		</select>
		<select id="rowDD" name="rowDD" style="display:none;">
			<option value="1">Row 1</option>
			<option value="2">Row 2</option>
			<option value="3">Row 3</option>
		</select>
		<select id="seatDD" name="seatDD" style="display:none;">
			<option value="1">Seat 1</option>
			<option value="2">Seat 2</option>
			<option value="3">Seat 3</option>
		</select>
	</div>
</body>

<footer>
	<script src="public/js/home.js"></script>
	<script src="public/js/jQuery/jquery-2.1.3.js"></script>
</footer>
